#!/usr/bin/env sh

main() {
    touch /tmp/lc0_healthcheck.log
    chown 1000:1000 /tmp/lc0_healthcheck.log

    # This doesn't cover backend errors, but it's better than nothing.
    IS_READY_RESPONSE="$(printf "%s\n" "isready" "quit" | /lczero/lc0 --logfile=/tmp/lc0_healthcheck.log )"

    if echo "${IS_READY_RESPONSE}" | grep -q "^readyok"; then
        return 0 # success
    fi

    echo "Engine Error: ${IS_READY_RESPONSE}"
    return 1
}

main "${@}"
exit $?
