#!/usr/bin/env sh

main() {
    IS_READY_RESPONSE="$(printf "%s\n" "isready" "quit" | nc -q 3 127.0.0.1 3333)"

    if echo "${IS_READY_RESPONSE}" | grep -q "^readyok"; then
        return 0 # success
    fi

    echo "Engine Error: ${IS_READY_RESPONSE}"
    return 1
}

main "${@}"
exit $?
