#!/usr/bin/env bash

main() {
    mkdir -p /lczero/resources

    local configTemplate="${LCZERO_CUSTOM_CONFIG_TEMPLATE:-/etc/templates/lc0.config.tpl}"

    if [ -n "${LCZERO_CUSTOM_CONFIG_TEMPLATE}" ]; then
        echo "> Custom config template specified"
    fi

    local networkFilename="${LCZERO_NETWORK_FILENAME:-}"
    local networksPath="${LCZERO_NETWORKS_PATH:?}"
    local networkSha="${LCZERO_NETWORK_SHA:-}"

    if [ -n "${networkFilename}" ] && [ -f "${networksPath}/${networkFilename}" ]; then
        LCZERO_WEIGHTS_FILE="${networksPath}/${networkFilename}"
    else
        LCZERO_WEIGHTS_FILE="${networksPath}/${networkSha}"
    fi

    export LCZERO_WEIGHTS_FILE

    echo "> Rendering lc0 config"
    /usr/local/bin/gomplate -V \
        -o /lczero/lc0.config \
        -f "${configTemplate}"
    return $?
}

main "${@}"
