version: "3.8"

services:
  server:
    image: ghcr.io/n0rthernl1ghts/lc0:latest
    ports:
      - "3333:3333/tcp"
    environment:
      LCZERO_BACKEND: "blas"
      LCZERO_BACKEND_OPTS: "blas_cores=4"
      LCZERO_THREADS: 2
      LCZERO_RAM_LIMIT_MB: 512
      LCZERO_VERBOSE_MOVE_STATS: "true"
      LCZERO_NETWORK_SHA: "d3afb47455f4318c397bbe257f4b149de497df6cf53dc142cf863bb4981cae05"
    volumes:
      - "./data/networks:/lczero/resources/networks"
    networks:
      default:
    deploy:
      restart_policy:
        condition: on-failure

networks:
  default:
