version: "3.8"

services:
  lczero:
    image: nlss/lczero
    ports:
      - "3333:3333/tcp"
    volumes:
      - "./data/networks:/lczero/resources/networks"
      - "./data/lc0.config:/lczero/resources/lc0.config"
    networks:
      default:
    deploy:
      restart_policy:
        condition: on-failure

networks:
  default:
