#!/command/with-contenv bash
# shellcheck shell=bash

# init-fix-permissions main
main() {
    # This will prepend service name to all output from here
    exec > >(while read -r line; do echo "[init-fix-permissions] ${line}"; done) 2>&1

    # Fix permissions
    chmod 0751 /lczero -Rv
    chmod 0751 /lczero/logs -Rv
    chmod 0770 /lczero/lc0 -Rv
    chmod 0770 /lczero/lc0_init -Rv
    chown lczero:lczero /lczero -Rv
}
main
