#!/usr/bin/env sh

downloadNetwork() {
    NETWORK_SHA="${1:?Missing network SHA}"
    curl --location \
         --request GET \
         --url "https://training.lczero.org/get_network?sha=${NETWORK_SHA}"\
         --output "/lczero/resources/networks/${NETWORK_SHA}"
    return $?
}

main() {
    mkdir -p /lczero/resources

    NETWORK_SHA="${LCZERO_NETWORK_SHA:?Missing network SHA}"

    echo "> Downloading resources"

    # Download the network
    if [ ! -f "/lczero/resources/networks/${NETWORK_SHA}" ]; then
        echo "> Downloading network ${NETWORK_SHA}"
        if ! downloadNetwork "${NETWORK_SHA}"; then
            echo "> Failed to download network ${NETWORK_SHA}"
            return 1
        fi

        echo "> Creating network symlink"
    fi

    ln -sf "/lczero/resources/networks/${NETWORK_SHA}" /lczero/resources/network
    return $?
}

main "${@}"
exit $?

