#!/usr/bin/env bash

downloadNetwork() {
    local networkSha="${1:?Missing network SHA}"
    local dlTarget="${2:?Missing download target}"

    curl --location \
        --request GET \
        --url "${LCZERO_NETWORK_GET_URI:?}${networkSha}" \
        --output "${dlTarget}"
    return $?
}

main() {
    mkdir -p /lczero/resources

    local networkSha="${LCZERO_NETWORK_SHA:-}"
    local networkFilename="${LCZERO_NETWORK_FILENAME:-}"
    local networksPath="${LCZERO_NETWORKS_PATH:?}"
    local networkPath

    if [ -n "${networkFilename}" ]; then
        echo "> LCZERO_NETWORK_FILENAME specified. Looking for network file in ${networksPath}"
        networkPath="${networksPath}/${networkFilename}"

        if [ ! -f "${networkPath}" ]; then
            echo "> Error: ${networkPath} was not found"
            echo "  Please add the weights file to ${networksPath} mount"
            return 1
        fi

        echo "> Found custom network file ${networkPath}"
        return 0

    fi

    echo "> Downloading resources"

    networkPath="${networksPath}/${networkSha}"

    # Download the network
    if [ ! -f "${networkPath}" ]; then
        local tempFile
        tempFile="$(mktemp)"
        echo "> Downloading network ${networkSha}"
        if ! downloadNetwork "${networkSha}" "${tempFile}"; then
            echo "> Failed to download network ${networkSha}"
            return 1
        fi

        echo "> Decompressing network"
        zcat "${tempFile}" >"${networkPath}"

        rm -f "${tempFile:?}"
    fi

    return 0
}

main "${@}"
