#!/usr/bin/env sh

downloadNetwork() {
    NETWORK_SHA="${1:?Missing network SHA}"
    DL_TARGET="${2:?Missing download target}"

    curl --location \
         --request GET \
         --url "https://training.lczero.org/get_network?sha=${NETWORK_SHA}"\
         --output "${DL_TARGET}"
    return $?
}

main() {
    mkdir -p /lczero/resources

    NETWORK_SHA="${LCZERO_NETWORK_SHA:-}"

    if [ -z "${NETWORK_SHA}" ] || [ "${NETWORK_SHA}" = "custom" ]; then
        echo "> No network specified, so none will be downloaded"
        echo "  Looking for network in /lczero-custom/network"

        if [ ! -f "/lczero-custom/network" ]; then
            echo "> No network found"
            echo "  Please mount a network to /lczero-custom/network"
            return 0
        fi

        echo "> Found custom network. Creating symlink"
        ln -sf "/lczero-custom/network" /lczero/resources/network
        return $?

    fi

    echo "> Downloading resources"

    # Download the network
    if [ ! -f "/lczero/resources/networks/${NETWORK_SHA}" ]; then
        TEMP_FILE="$(mktemp)"
        echo "> Downloading network ${NETWORK_SHA}"
        if ! downloadNetwork "${NETWORK_SHA}" "${TEMP_FILE}"; then
            echo "> Failed to download network ${NETWORK_SHA}"
            return 1
        fi

        echo "> Decompressing network"
        zcat "${TEMP_FILE}" > "/lczero/resources/networks/${NETWORK_SHA}"

        rm -f "${TEMP_FILE:?}"
    fi

    echo "> Creating network symlink"
    ln -sf "/lczero/resources/networks/${NETWORK_SHA}" /lczero/resources/network
    return $?
}

main "${@}"
exit $?

