#!/usr/bin/env sh

main() {
    mkdir -p /lczero/resources

    CONFIG_TEMPLATE="${LCZERO_CUSTOM_CONFIG_TEMPLATE:-/etc/templates/lc0.config.tpl}"

    if [ -n "${LCZERO_CUSTOM_CONFIG_TEMPLATE}" ]; then
        echo "> Custom config template specified"
    fi

    if [ -n "${LCZERO_NETWORK_FILENAME}" ] && [ -f "${LCZERO_NETWORKS_PATH}/${LCZERO_NETWORK_FILENAME}" ]; then
        export LCZERO_WEIGHTS_FILE="${LCZERO_NETWORKS_PATH}/${LCZERO_NETWORK_FILENAME}"
    else
        export LCZERO_WEIGHTS_FILE="${LCZERO_NETWORKS_PATH}/${LCZERO_NETWORK_SHA}"
    fi

    echo "> Rendering lc0 config"
    /usr/local/bin/gomplate -V \
        -o /lczero/lc0.config \
        -f "${CONFIG_TEMPLATE}"
    return $?
}

main "${@}"
exit $?
